apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init-user
spec:
  ## Uncomment the line below if enable auto cleanup the job pod
  # ttlSecondsAfterFinished: 300

  # Retry at most 2 times
  backoffLimit: 2

  template:
    metadata:
      labels:
        app.role: apps

    spec:
      affinity:
        {{- if .Values.airflow.affinity }}
          {{- toYaml .Values.airflow.affinity | nindent 8 }}
        {{- else }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.role: apps
              topologyKey: kubernetes.io/hostname
            weight: 100
        {{- end }}

      containers:
      - name: airflow-init-user
        imagePullPolicy: IfNotPresent

        image: "{{ .Values.airflow.images.airflow.repository }}:{{ .Values.airflow.images.airflow.tag }}"

        # Add any command arguments or environment variables needed
        # Notes: airflow dags command requires an airflow connected
        # environment, move those to makefile targets will be eaiser
        command: ["/bin/bash"]
        args:
        - -c
        - |
          echo "User: `id`"
          echo "PWD: `pwd`"
          echo "----"
          echo "Apply patches ..."
          python3 ~/airflow/run/auto-news/src/patches.py
          echo "Apply patches finished"
          echo "----"
          echo "Job finished"

      # Ensures the job runs only once
      restartPolicy: Never

      {{ if .Values.airflow.registry.secretName  }}
      imagePullSecrets:
        - name: {{ .Values.airflow.registry.secretName }}
      {{ end }}
