name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        mkdir -p build
        cp .env.template build/.env
        docker build . --file build/Dockerfile --tag autonews-github-action:$(date +%s)
