name: auto-news
description: A Helm Chart for auto-news
version: 1.0.0
apiVersion: v2
keywords:
    - auto-news
home: https://github.com/finaldie/auto-news
sources:
  - https://github.com/finaldie/auto-news

maintainers:
  - email: hyzwowtools@gmail.com
    name: Yuzhang Hu

type: application

# User could decide use the below dependencies or setup their own
dependencies:
- name: milvus
  version: '4.1.29'
  repository: https://zilliztech.github.io/milvus-helm
  condition: milvus.enabled

- name: airflow
  version: '1.13.1'
  repository: https://airflow.apache.org
  # condition: airflow.enabled

- name: mysql
  version: '10.1.0'
  repository: https://charts.bitnami.com/bitnami
  condition: mysql.enabled

- name: adminer
  version: '0.2.1'
  repository: https://cetic.github.io/helm-charts
  condition: adminer.enabled

- name: redis
  version: '19.0.1'
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
