name: Python CI (Deps)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/requirements.txt

    # Add additional steps here for your testing or validation process
    # - name: Build docker image
    #   run: |
    #     mkdir -p build
    #     cp .env.template build/.env
    #     docker build . --file build/Dockerfile --tag autonews-github-action:$(date +%s)
